### ISSUE TITLE
still old problem 

### ISSUE THREAD

**Issue by pizza23** [niranjan94/show-java#9] opened 2015-09-07 19:55 UTC
Optimizing dex file ... takes forever :/

**Comment by NotANoob** [comment] 2015-09-08 17:32
I had the same problem I just did 
Settings>Apps>Show Java>Clear Data
and it worked fine

**Comment by niranjan94** [comment] 2015-09-09 13:42
@pizza23 .. I'm closing this issue for now. If I'm able to reproduce it, or if I get reports of the same from more users, I'll reopen this ...

**Closed by niranjan94** 2015-09-09 13:42 UTC
Labels: bug, help wanted

**Comment by pizza23** [comment] 2015-09-09 14:01
Hello,

 

happy news !!!!  :)

 

Settings>Application manager>Show Java>Clear Data (Clear cache)

 

DID THE TRICK !!!  IT WORKS NOW !!!   :)))))))

 

Regard,

Stan

**Comment by pizza23** [comment] 2015-09-09 14:01
Hello,

 

happy news !!!!  :)

 

Settings>Application manager>Show Java>Clear Data (Clear cache)

 

DID THE TRICK !!!  IT WORKS NOW !!!   :)))))))

 

Regard,

Stan

  

************************************************************

**Comment by OwnageIsMagic** [comment] 2015-09-14 17:23
it appears after update from market
complete reinstall solves the problem

**Comment by niranjan94** [comment] 2015-09-14 17:45
Clearing data and cache seems to be perfect fix to this weird issue as of
now.
